import React from 'react';
import './Animation.css'
import { FaYoutube } from 'react-icons/fa';

const testimonials = [
  {
    name: 'Paul Xue',
    username: '@pxue',
    quote: 'Worked very very well, the content generated by the AI was exactly what I wanted. I used it extensively as an idea generator to help me break writers block. The AI template feature is also something I loved, it nudges the content towards my exact tone and voice.',
    highlight: '',
    profilePic: 'https://randomuser.me/api/portraits/men/32.jpg',
  },
  {
    name: 'Martijn',
    username: '@mrtnxyz',
    quote: 'I had a few company X accounts with a very small amount of followers. At the moment I started using Snowball it grew my accounts significantly. Honestly looking forward to all the features that are in BETA. I will definitely share this amazing tool with my network. Thanks for making my life easier!',
    highlight: '',
    profilePic: 'https://randomuser.me/api/portraits/men/75.jpg',
  },
  {
    name: 'Jacob Boston',
    username: '@jacob_boston',
    quote: 'This will be great for those who do use the platform and need some help with posting more frequently. (of maybe those like me who might want to hop on and don\'t know where to start lol) Great job including the different tones & adding variety to your product. 👏',
    highlight: '',
    profilePic: 'https://randomuser.me/api/portraits/men/64.jpg',
  },
  {
    name: 'Jorge Medina',
    username: '@thejorgemedina',
    quote: 'Exciting new tech for all of those wanting to grow on X. Engagement is super important but very time consuming!',
    highlight: '',
    profilePic: 'https://randomuser.me/api/portraits/men/81.jpg',
  },
  {
    name: 'Mateusz Siatrak',
    username: '@mateusz_siatrak',
    quote: 'It’s very hard to grow in the space of social media by going vanilla. Snowball gives people the extra edge to grow faster. Great product!',
    highlight: '',
    profilePic: 'https://randomuser.me/api/portraits/men/51.jpg',
  },
  {
    name: 'Jonni Gani',
    username: '@jgani',
    quote: 'Such a useful tool :) Definitely the best I’ve tested in its category. #VeryHappyCustomer',
    highlight: '',
    profilePic: 'https://randomuser.me/api/portraits/women/68.jpg',
  },
];

function TestimonialCard({ testimonial }) {
  const displayText = testimonial.highlight || testimonial.quote;

  return (
    <div className="bg-white shadow-lg rounded-lg p-6 mb-6 border-t-4 border-gray-300 h-auto flex flex-col justify-between transition-transform transform hover:scale-105 hover:shadow-xl duration-300 ease-in-out opacity-0 animate-fadeIn">
      <p className="text-gray-800 mb-4 text-base leading-relaxed">
        {displayText}
      </p>
      <hr className="my-4 border-gray-300" />
      <div className="flex items-center justify-between mt-auto">
        <div className="flex items-center">
          <img src={testimonial.profilePic} alt="Profile" className="rounded-full mr-3 w-10 h-10 object-cover" />
          <div>
            <p className="font-bold text-sm">{testimonial.name}</p>
            <p className="text-gray-500 text-xs">{testimonial.username}</p>
          </div>
        </div>
        <FaYoutube className="text-red-500 text-2xl" />
      </div>
    </div>
  );
}

function Testimonials() {
  return (
    <div className="w-full bg-[#F7FAFC] text-center justify-center font-inter mt-28 py-20 px-4 sm:px-6 lg:px-8">
      <h2 className="text-center justify-center text-4xl lg:text-5xl font-bold tracking-tight !leading-[1.15]]">
        Join Thousands Of Shorts Creators <br className='hidden lg:block md:block' />With Success
      </h2>
      <p className='text-gray-500 mt-5 text-md lg:text-lg'>Look At Insightful Thoughts From Our Customers.</p>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2 lg:gap-10 mt-12 max-w-7xl mx-auto">
        {testimonials.map((testimonial, index) => (
          <TestimonialCard key={index} testimonial={testimonial} />
        ))}
      </div>
    </div>
  );
}

export default Testimonials;
